#!/bin/bash
basename=${1%.*}
cmd="g++ -I/home/jack/src/fltk-1.3 -I/usr/include/freetype2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT -o $basename $1 ../../fltk-1.3/lib/libfltk.a -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11 -lportaudio"
echo $cmd
`$cmd`
