#!/bin/bash
csound=/home/jack/src/csound5
if [ $# != 1 ]
then
  echo "Arg! Missing argument."
  exit
fi
wd=`pwd`
cd $csound
cmd="g++ -ggdb -o $wd/$1 -I H/ -I Top/ -I interfaces/ -I frontends/CsoundAC/ $wd/$1.cpp libcsnd.so libcsound64.a libCsoundAC.a"
#cmd="g++ -o $wd/$1 -I H/ -I interfaces/ -I frontends/CsoundAC/ $wd/$1.cpp libcsnd.so libCsoundAC.a"
echo $cmd
`$cmd`
cd $wd
