// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef fluid_test_h
#define fluid_test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Light_Button.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Light_Button *sawWaveButton;
private:
  void cb_sawWaveButton_i(Fl_Light_Button*, void*);
  static void cb_sawWaveButton(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *midiThroughButton;
private:
  void cb_midiThroughButton_i(Fl_Light_Button*, void*);
  static void cb_midiThroughButton(Fl_Light_Button*, void*);
public:
  Fl_Light_Button *midiSynthButton;
private:
  void cb_midiSynthButton_i(Fl_Light_Button*, void*);
  static void cb_midiSynthButton(Fl_Light_Button*, void*);
};
#endif
